<?php

namespace App\Http\Controllers\Kecamatan;

use App\Http\Controllers\Controller;
use App\Models\Umkm;
use App\Models\UmkmAdminLog;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Models\Desa;

class LayananPublikController extends Controller
{
    /**
     * --- UMKM RAKYAT FACILITATOR SECTION ---
     * Menggantikan fungsi UMKM lama dengan sistem UMKM Rakyat.
     */

    public function umkmIndex(Request $request)
    {
        $query = Umkm::latest();

        if ($request->has('q')) {
            $query->where('nama_usaha', 'like', '%' . $request->q . '%')
                ->orWhere('nama_pemilik', 'like', '%' . $request->q . '%');
        }

        $umkm = $query->paginate(10);
        return view('kecamatan.layanan.umkm.index', compact('umkm'));
    }

    public function umkmCreate(Request $request)
    {
        // Form "Bantu Daftarkan UMKM"
        $desas = Desa::orderBy('nama_desa')->get();

        // Auto-fill dari inbox (jika ada)
        $prefill = [
            'from_inbox' => $request->query('from_inbox'),
            'nama_pemilik' => $request->query('nama'),
            'no_wa' => $request->query('wa'),
            'desa' => $request->query('desa') ? Desa::find($request->query('desa'))?->nama_desa : null,
        ];

        return view('kecamatan.layanan.umkm.form_bantuan', compact('desas', 'prefill'));
    }

    public function umkmStore(Request $request)
    {
        $validated = $request->validate([
            'nama_usaha' => 'required|string|max:255',
            'nama_pemilik' => 'required|string|max:255',
            'no_wa' => 'required|string|max:20', // Format 62...
            'jenis_usaha' => 'required|string|max:100',
            'desa' => 'required|string',
            'notes' => 'nullable|string', // Catatan bantuan
        ]);

        // Create UMKM
        $umkm = new Umkm();
        $umkm->nama_usaha = $validated['nama_usaha'];
        $umkm->nama_pemilik = $validated['nama_pemilik'];
        $umkm->no_wa = $validated['no_wa'];
        $umkm->jenis_usaha = $validated['jenis_usaha'];
        $umkm->desa = $validated['desa'];

        // System fields
        $umkm->source = 'admin'; // created_by kecamatan
        $umkm->status = 'aktif'; // Langsung aktif agar bisa langsung dikelola, tapi butuh handover
        $umkm->ownership_status = 'pending_transfer'; // Menunggu warga ambil alih via link

        $umkm->save(); // Slug & Token generated by Model Boot

        // Log Action
        UmkmAdminLog::create([
            'umkm_id' => $umkm->id,
            'action' => 'create',
            'actor' => 'admin', // Kecamatan
            'notes' => 'Pendaftaran jalur bantuan (Fasilitator). ' . ($validated['notes'] ?? ''),
        ]);

        // Redirect to Handover Page
        return redirect()->route('kecamatan.umkm.handover', $umkm->id)
            ->with('success', 'UMKM berhasil didaftarkan. Segera lakukan serah terima digital.');
    }

    public function umkmHandover($id)
    {
        $umkm = Umkm::findOrFail($id);

        // Generate Link
        $manageLink = route('umkm_rakyat.manage', $umkm->manage_token);

        // WhatsApp Message generator
        $waMessage = "Halo {$umkm->nama_pemilik},\n\n";
        $waMessage .= "Berikut adalah link akses untuk mengelola Lapak UMKM Anda ({$umkm->nama_usaha}).\n\n";
        $waMessage .= "Silakan klik link ini untuk mulai melengkapi produk dan foto:\n";
        $waMessage .= $manageLink . "\n\n";
        $waMessage .= "Simpan link ini baik-baik. Jangan berikan kepada orang lain.";

        $waUrl = "https://wa.me/{$umkm->no_wa}?text=" . urlencode($waMessage);

        return view('kecamatan.layanan.umkm.handover', compact('umkm', 'manageLink', 'waUrl', 'waMessage'));
    }

    public function umkmEdit($id)
    {
        // Kecamatan TIDAK BOLEH mengedit data produk/harga.
        // Hanya boleh mengedit data administratif dasar jika ada kesalahan ketik saat input awal.
        $umkm = Umkm::findOrFail($id);
        $desas = Desa::orderBy('nama_desa')->get();
        return view('kecamatan.layanan.umkm.edit_admin', compact('umkm', 'desas'));
    }

    public function umkmUpdate(Request $request, $id)
    {
        $umkm = Umkm::findOrFail($id);

        $validated = $request->validate([
            'nama_usaha' => 'required|string|max:255',
            'nama_pemilik' => 'required|string|max:255',
            'no_wa' => 'required|string|max:20',
            'jenis_usaha' => 'required|string',
            'desa' => 'required|string',
        ]);

        $umkm->update($validated);

        UmkmAdminLog::create([
            'umkm_id' => $umkm->id,
            'action' => 'verify', // Reuse verify/update action
            'actor' => 'admin',
            'notes' => 'Koreksi data administratif oleh kecamatan.',
        ]);

        return redirect()->route('kecamatan.umkm.index')->with('success', 'Data administratif UMKM diperbarui.');
    }

    public function umkmDestroy($id)
    {
        $umkm = Umkm::findOrFail($id);
        $umkm->delete();

        return redirect()->route('kecamatan.umkm.index')->with('success', 'UMKM dinonaktifkan/dihapus.');
    }

    public function resetAkses($id)
    {
        // Generate Token Baru jika warga kehilangan akses
        $umkm = Umkm::findOrFail($id);
        $umkm->manage_token = Str::random(40);
        $umkm->save();

        UmkmAdminLog::create([
            'umkm_id' => $umkm->id,
            'action' => 'activate',
            'actor' => 'admin',
            'notes' => 'Reset akses (Token baru) atas permintaan warga.',
        ]);

        return redirect()->route('kecamatan.umkm.handover', $umkm->id)
            ->with('success', 'Akses UMKM berhasil di-reset. Silakan berikan link baru.');
    }

    /**
     * --- JOB VACANCY SECTION (Legacy/Existing) ---
     */

    public function lokerIndex()
    {
        $loker = \App\Models\JobVacancy::latest()->paginate(10);
        return view('kecamatan.layanan.loker.index', compact('loker'));
    }

    public function lokerCreate()
    {
        return view('kecamatan.layanan.loker.form');
    }

    public function lokerStore(Request $request)
    {
        $validated = $request->validate([
            'title' => 'required|string|max:255',
            'company_name' => 'required|string|max:255',
            'contact_wa' => 'required|string|max:20',
            'description' => 'required|string',
            'is_active' => 'required|boolean',
        ]);

        \App\Models\JobVacancy::create($validated);

        return redirect()->route('kecamatan.loker.index')->with('success', 'Data Lowongan Kerja berhasil ditambahkan.');
    }

    public function lokerEdit($id)
    {
        $loker = \App\Models\JobVacancy::findOrFail($id);
        return view('kecamatan.layanan.loker.form', compact('loker'));
    }

    public function lokerUpdate(Request $request, $id)
    {
        $loker = \App\Models\JobVacancy::findOrFail($id);
        // ... (existing validation)
        $validated = $request->validate([
            'title' => 'required|string|max:255',
            'company_name' => 'required|string|max:255',
            'contact_wa' => 'required|string|max:20',
            'description' => 'required|string',
            'is_active' => 'required|boolean',
        ]);
        $loker->update($validated);

        return redirect()->route('kecamatan.loker.index')->with('success', 'Data Lowongan Kerja berhasil diperbarui.');
    }

    public function lokerDestroy($id)
    {
        $loker = \App\Models\JobVacancy::findOrFail($id);
        $loker->delete();

        return redirect()->route('kecamatan.loker.index')->with('success', 'Data Lowongan Kerja berhasil dihapus.');
    }
}
